export enum InvalidInstructionReason {
  UnknownReason = 'UNKNOWN_REASON',
  BasicInstructionInvalid = 'BASIC_INSTRUCTION_INVALID',
  BasicInstructionWithNonWritableNote = 'BASIC_INSTRUCTION_WITH_NON_WRITABLE_NOTE',
  UnidentifiedMethodInstruction = 'UNIDENTIFIED_METHOD_INSTRUCTION',
  UnknownMethodInstruction = 'UNKNOWN_METHOD_INSTRUCTION',
  FooterInstructionWithoutArguments = 'FOOTER_INSTRUCTION_WITHOUT_ARGUMENTS',
  FooterInstructionWithUnmappedArguments = 'FOOTER_INSTRUCTION_WITH_UNMAPPED_ARGUMENTS',
  FooterInstructionWithInvalidFooter = 'FOOTER_INSTRUCTION_WITH_INVALID_FOOTER',
  HeaderInstructionWithoutArguments = 'HEADER_INSTRUCTION_WITHOUT_ARGUMENTS',
  HeaderInstructionWithUnmappedArguments = 'HEADER_INSTRUCTION_WITH_UNMAPPED_ARGUMENTS',
  HeaderInstructionWithInvalidHeader = 'HEADER_INSTRUCTION_WITH_INVALID_HEADER',
  MergeInstructionWithoutTargets = 'MERGE_INSTRUCTION_WITHOUT_TARGETS',
  MergeInstructionWithUnmergeableTargets = 'MERGE_INSTRUCTION_WITH_UNMERGEABLE_TARGETS',
  MergeInstructionTargetsWithNonWritableNotes = 'MERGE_INSTRUCTION_TARGETS_WITH_NON_WRITABLE_NOTES',
  MergeInstructionTargetsWithConcurrentNotes = 'MERGE_INSTRUCTION_TARGETS_WITH_CONCURRENT_NOTES',
  RepeatInstructionWithoutArguments = 'REPEAT_INSTRUCTION_WITHOUT_ARGUMENTS',
  RepeatInstructionWithUnmappedArguments = 'REPEAT_INSTRUCTION_WITH_UNMAPPED_ARGUMENTS',
  RepeatInstructionWithInvalidRepetitionsValueType = 'REPEAT_INSTRUCTION_WITH_INVALID_REPETITIONS_VALUE_TYPE',
  RepeatInstructionWithInvalidRepetitionsValue = 'REPEAT_INSTRUCTION_WITH_INVALID_REPETITIONS_VALUE',
  RepeatInstructionWithoutTargets = 'REPEAT_INSTRUCTION_WITHOUT_TARGETS',
  RepeatInstructionWithInvalidTargets = 'REPEAT_INSTRUCTION_WITH_INVALID_TARGETS',
  SpacingInstructionWithoutArguments = 'SPACING_INSTRUCTION_WITHOUT_ARGUMENTS',
  SpacingInstructionWithUnmappedArguments = 'SPACING_INSTRUCTION_WITH_UNMAPPED_ARGUMENTS',
  SpacingInstructionWithInvalidSpacingValueType = 'SPACING_INSTRUCTION_WITH_INVALID_SPACING_VALUE_TYPE',
  SpacingInstructionWithInvalidSpacingValue = 'SPACING_INSTRUCTION_WITH_INVALID_SPACING_VALUE',
}
