version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "prettier"
        versions:
          - "2.x"
