name: CI

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint project files
        run: npm run lint

      - name: Check code formatting
        run: npm run prettier:check

      - name: Run tests
        run: npm run test:coverage

      - name: Coveralls parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-version-${{ matrix.node-version }}
          parallel: true

      - name: Build project
        run: npm run build

  finish:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
